spring:
  datasource:
    url: # db url
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: # username
    password: # password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

side-api:
  check-ip-url: http://www.geoplugin.net/json.gp?ip=%s
server:
  port: 5000